/**
 * detect-ip.js
 * Tự động phát hiện IP local của máy và ghi vào cms-middle-fe/.env.local
 * Được chạy trước lệnh `yarn dev` để Vite có thể đọc VITE_HOST đúng.
 *
 * Thứ tự ưu tiên interface:
 *   1. Ethernet (không phải vEthernet)
 *   2. Wi-Fi
 *   3. Bất kỳ IPv4 không phải loopback còn lại
 *
 * Các interface bị loại bỏ: Tailscale, vEthernet, Loopback, VMware, VirtualBox
 */

const os = require('os');
const fs = require('fs');
const path = require('path');

// ─── Đọc giá trị fallback từ .env gốc ─────────────────────────────────────
function parseDotEnv(filePath) {
  const result = {};
  if (!fs.existsSync(filePath)) return result;
  const lines = fs.readFileSync(filePath, 'utf-8').split('\n');
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eqIdx = trimmed.indexOf('=');
    if (eqIdx === -1) continue;
    const key = trimmed.slice(0, eqIdx).trim();
    const value = trimmed.slice(eqIdx + 1).trim();
    result[key] = value;
  }
  return result;
}

// ─── Phát hiện IP local ────────────────────────────────────────────────────
const SKIP_KEYWORDS = ['Tailscale', 'vEthernet', 'Loopback', 'VMware', 'VirtualBox', 'Pseudo'];

function getLocalIP() {
  const interfaces = os.networkInterfaces();
  const candidates = [];

  for (const [name, addrs] of Object.entries(interfaces)) {
    if (SKIP_KEYWORDS.some(kw => name.includes(kw))) continue;

    for (const iface of addrs) {
      if (iface.family === 'IPv4' && !iface.internal) {
        candidates.push({ name, address: iface.address });
      }
    }
  }

  if (candidates.length === 0) return null;

  // Ưu tiên Ethernet thực > Wi-Fi > còn lại
  const preferred =
    candidates.find(c => /ethernet/i.test(c.name) && !/vethernet/i.test(c.name)) ||
    candidates.find(c => /wi.fi|wlan|wireless/i.test(c.name)) ||
    candidates[0];

  return preferred?.address || null;
}

// ─── Tìm cổng trống ─────────────────────────────────────────────────────────
function findFreePort(startPort) {
  return new Promise((resolve) => {
    const server = require('net').createServer();
    server.listen(startPort, () => {
      const port = server.address().port;
      server.close(() => resolve(port));
    });
    server.on('error', (e) => {
      if (e.code === 'EADDRINUSE') {
        resolve(findFreePort(startPort + 1));
      } else {
        resolve(startPort);
      }
    });
  });
}

// ─── Main ──────────────────────────────────────────────────────────────────
(async function main() {
  const ROOT_DIR = path.join(__dirname, '..');
  const FE_DIR = path.join(ROOT_DIR, 'cms-middle-fe');
  const ROOT_ENV_FILE = path.join(ROOT_DIR, '.env');
  const ROOT_ENV_GEN_FILE = path.join(ROOT_DIR, '.env.generated');
  const ENV_LOCAL_FILE = path.join(FE_DIR, '.env.local');

  const fallback = parseDotEnv(ROOT_ENV_FILE);
  const detectedIP = getLocalIP();
  const fallbackHost = '127.0.0.1'; // Bỏ fallback host từ FE .env, chỉ ưu tiên auto-detect
  const finalIP = detectedIP || fallbackHost;

  if (!detectedIP) {
    console.warn(`[detect-ip] ⚠️  Không tìm thấy IP local hợp lệ. Dùng fallback: ${fallbackHost}`);
  } else {
    console.log(`[detect-ip] ✅ IP được phát hiện: ${finalIP}`);
  }

  // Lấy PORT từ .env gốc
  const fePort = fallback['FE_PORT'] || '5051';
  const initialBePort = parseInt(fallback['BE_PORT'] || '5050', 10);
  const bePort = await findFreePort(initialBePort);

  if (bePort !== initialBePort) {
    console.log(`[detect-ip] ⚠️ Cổng ${initialBePort} đang bận, tự động chuyển sang cấu hình chạy cổng: ${bePort}`);
  }

  // Nội dung dành cho Vite (Frontend .env.local)
  const feEnvContent = `# Auto-generated by scripts/detect-ip.js — DO NOT EDIT MANUALLY
VITE_HOST=${finalIP}
VITE_PORT=${fePort}
VITE_BE_HOST=${finalIP}
VITE_BE_PORT=${bePort}
`;

  // Nội dung dành cho Backend (.env.generated)
  const beEnvContent = `# Auto-generated by scripts/detect-ip.js — DO NOT EDIT MANUALLY
LOCAL_IP=${finalIP}
FE_PORT=${fePort}
BE_PORT=${bePort}
`;

  fs.writeFileSync(ENV_LOCAL_FILE, feEnvContent, 'utf-8');
  fs.writeFileSync(ROOT_ENV_GEN_FILE, beEnvContent, 'utf-8');

  console.log(`[detect-ip] 📝 Đã ghi: ${ENV_LOCAL_FILE} (cho Vite)`);
  console.log(`[detect-ip] 📝 Đã ghi: ${ROOT_ENV_GEN_FILE} (cho Backend)`);
})();
